# Data Collection

## Objective

The purpose of this notebook is to collect historical daily market data for Bitcoin (BTC), Ethereum (ETH), Gold (GLD), and the S&P 500 Index using the Yahoo Finance API.

The collected datasets will serve as the primary data source for subsequent preprocessing, exploratory data analysis, statistical modeling, and financial analysis.

This notebook also performs an initial assessment of data completeness before storing the datasets in the project's raw data directory.

In [34]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import yfinance as yf

from pathlib import Path

In [35]:
# Create project directories if they do not already exist

RAW_DATA_PATH = Path("crypto_project/data/raw")
RAW_DATA_PATH.mkdir(parents=True, exist_ok=True)

print("Raw data directory is ready.")

Raw data directory is ready.

In [36]:
assets = {
    "Bitcoin": "BTC-USD",
    "Ethereum": "ETH-USD",
    "Gold": "GLD",
    "SP500": "^GSPC"
}

In [37]:
#data downloading

market_data = {}

for asset_name, ticker in assets.items():

    print(f"Downloading {asset_name}...")

    df = yf.download(
        ticker,
        start="2019-01-01",
        end="2025-01-01",
        auto_adjust=True,
        progress=False
    )

    df.reset_index(inplace=True)

    market_data[asset_name] = df

print("Download Complete.")

Downloading Bitcoin...
Downloading Ethereum...
Downloading Gold...
Downloading SP500...
Download Complete.

In [38]:
# Data Inspection

for asset_name, df in market_data.items():

    print("="*60)
    print(asset_name)

    display(df.head())

    print(df.info())

============================================================
Bitcoin

Price,Date,Close,High,Low,Open,Volume
Ticker,,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
0,2019-01-01,3843.520020,3850.913818,3707.231201,3746.713379,4324200990
1,2019-01-02,3943.409424,3947.981201,3817.409424,3849.216309,5244856836
2,2019-01-03,3836.741211,3935.685059,3826.222900,3931.048584,4530215219
3,2019-01-04,3857.717529,3865.934570,3783.853760,3832.040039,4847965467
4,2019-01-05,3845.194580,3904.903076,3836.900146,3851.973877,5137609824

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Date, )           2192 non-null   datetime64[ns]
 1   (Close, BTC-USD)   2192 non-null   float64
 2   (High, BTC-USD)    2192 non-null   float64
 3   (Low, BTC-USD)     2192 non-null   float64
 4   (Open, BTC-USD)    2192 non-null   float64
 5   (Volume, BTC-USD)  2192 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 102.9 KB
None
============================================================
Ethereum

Price        Date       Close        High         Low        Open      Volume
Ticker                ETH-USD     ETH-USD     ETH-USD     ETH-USD     ETH-USD
0      2019-01-01  140.819412  141.397507  132.650711  133.418152  2258709868
1      2019-01-02  155.047684  156.929138  140.650955  141.519516  3328240369
2      2019-01-03  149.135010  155.863052  147.198364  155.196045  2676164880
3      2019-01-04  154.581940  156.878983  147.907104  148.912888  3126192535
4      2019-01-05  155.638596  160.824890  154.337418  154.337418  3338211928

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Date, )           2192 non-null   datetime64[ns]
 1   (Close, ETH-USD)   2192 non-null   float64
 2   (High, ETH-USD)    2192 non-null   float64
 3   (Low, ETH-USD)     2192 non-null   float64
 4   (Open, ETH-USD)    2192 non-null   float64
 5   (Volume, ETH-USD)  2192 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 102.9 KB
None
============================================================
Gold

Price        Date       Close        High         Low        Open    Volume
Ticker                    GLD         GLD         GLD         GLD       GLD
0      2019-01-02  121.330002  121.750000  120.879997  121.349998  12776200
1      2019-01-03  122.430000  122.459999  121.730003  121.779999  15440800
2      2019-01-04  121.440002  121.599998  120.690002  121.320000  13334000
3      2019-01-07  121.860001  122.220001  121.570000  122.160004   7473600
4      2019-01-08  121.529999  121.709999  121.059998  121.150002   7643100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1510 entries, 0 to 1509
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   (Date, )       1510 non-null   datetime64[ns]
 1   (Close, GLD)   1510 non-null   float64
 2   (High, GLD)    1510 non-null   float64
 3   (Low, GLD)     1510 non-null   float64
 4   (Open, GLD)    1510 non-null   float64
 5   (Volume, GLD)  1510 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 70.9 KB
None
============================================================
SP500

Price,Date,Close,High,Low,Open,Volume
Ticker,,^GSPC,^GSPC,^GSPC,^GSPC,^GSPC
0,2019-01-02,2510.030029,2519.489990,2467.469971,2476.959961,3733160000
1,2019-01-03,2447.889893,2493.139893,2443.959961,2491.919922,3858830000
2,2019-01-04,2531.939941,2538.070068,2474.330078,2474.330078,4234140000
3,2019-01-07,2549.689941,2566.159912,2524.560059,2535.610107,4133120000
4,2019-01-08,2574.409912,2579.820068,2547.560059,2568.110107,4120060000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1510 entries, 0 to 1509
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   (Date, )         1510 non-null   datetime64[ns]
 1   (Close, ^GSPC)   1510 non-null   float64
 2   (High, ^GSPC)    1510 non-null   float64
 3   (Low, ^GSPC)     1510 non-null   float64
 4   (Open, ^GSPC)    1510 non-null   float64
 5   (Volume, ^GSPC)  1510 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 70.9 KB
None

In [39]:
# Data Quality Assessment

summary = []

for asset_name, df in market_data.items():

    summary.append({

        "Asset": asset_name,

        "Rows": len(df),

        "Columns": df.shape[1],

        "Missing Values": df.isna().sum().sum(),

        "Start Date": df["Date"].min(),

        "End Date": df["Date"].max()

    })

summary_df = pd.DataFrame(summary)

summary_df

      Asset  Rows  Columns  Missing Values Start Date   End Date
0   Bitcoin  2192        6               0 2019-01-01 2024-12-31
1  Ethereum  2192        6               0 2019-01-01 2024-12-31
2      Gold  1510        6               0 2019-01-02 2024-12-31
3     SP500  1510        6               0 2019-01-02 2024-12-31

In [40]:
# Saving raw data

for asset_name, df in market_data.items():
     # Flatten MultiIndex columns if present
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    filename = asset_name.lower() + ".csv"
    df.to_csv(RAW_DATA_PATH / filename, index=False)

print("All raw datasets saved successfully.")

PermissionError: [Errno 13] Permission denied: 'crypto_project\\data\\raw\\bitcoin.csv'

# Summary

The historical market data for Bitcoin, Ethereum, Gold, and the S&P 500 were successfully collected using the Yahoo Finance API.

The datasets were inspected for completeness and exported to the project's raw data directory. These files will be used in the next notebook for data cleaning and preprocessing.

### Next Step

Notebook 02 — Data Cleaning & Preprocessing