# Data Cleaning & Preprocessing

## Objective

The objective of this notebook is to clean, standardize, and integrate the historical datasets collected from Yahoo Finance into a single analysis-ready dataset.

The preprocessing steps ensure data consistency and improve the quality of subsequent exploratory analysis and statistical modeling.

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
RAW_DATA_PATH = Path("crypto_project/data/raw")

PROCESSED_DATA_PATH = Path("crypto_project/data/processed")

PROCESSED_DATA_PATH.mkdir(parents=True, exist_ok=True)

In [3]:
bitcoin = pd.read_csv(RAW_DATA_PATH / "bitcoin.csv")

ethereum = pd.read_csv(RAW_DATA_PATH / "ethereum.csv")

gold = pd.read_csv(RAW_DATA_PATH / "gold.csv")

sp500 = pd.read_csv(RAW_DATA_PATH / "sp500.csv")

In [4]:
datasets = {
    "Bitcoin": bitcoin,
    "Ethereum": ethereum,
    "Gold": gold,
    "SP500": sp500
}

In [5]:
#dataset overview

for name, df in datasets.items():

    print("="*60)
    print(name)
    print(df.shape)
    display(df.head())

============================================================
Bitcoin
(2192, 6)

         Date        Close         High          Low         Open      Volume
0  2019-01-01  3843.520020  3850.913818  3707.231201  3746.713379  4324200990
1  2019-01-02  3943.409424  3947.981201  3817.409424  3849.216309  5244856836
2  2019-01-03  3836.741211  3935.685059  3826.222900  3931.048584  4530215219
3  2019-01-04  3857.717529  3865.934570  3783.853760  3832.040039  4847965467
4  2019-01-05  3845.194580  3904.903076  3836.900146  3851.973877  5137609824

============================================================
Ethereum
(2192, 6)

         Date       Close        High         Low        Open      Volume
0  2019-01-01  140.819412  141.397507  132.650711  133.418152  2258709868
1  2019-01-02  155.047684  156.929138  140.650955  141.519516  3328240369
2  2019-01-03  149.135010  155.863052  147.198364  155.196045  2676164880
3  2019-01-04  154.581940  156.878983  147.907104  148.912888  3126192535
4  2019-01-05  155.638596  160.824890  154.337418  154.337418  3338211928

============================================================
Gold
(1510, 6)

         Date       Close        High         Low        Open    Volume
0  2019-01-02  121.330002  121.750000  120.879997  121.349998  12776200
1  2019-01-03  122.430000  122.459999  121.730003  121.779999  15440800
2  2019-01-04  121.440002  121.599998  120.690002  121.320000  13334000
3  2019-01-07  121.860001  122.220001  121.570000  122.160004   7473600
4  2019-01-08  121.529999  121.709999  121.059998  121.150002   7643100

============================================================
SP500
(1510, 6)

         Date        Close         High          Low         Open      Volume
0  2019-01-02  2510.030029  2519.489990  2467.469971  2476.959961  3733160000
1  2019-01-03  2447.889893  2493.139893  2443.959961  2491.919922  3858830000
2  2019-01-04  2531.939941  2538.070068  2474.330078  2474.330078  4234140000
3  2019-01-07  2549.689941  2566.159912  2524.560059  2535.610107  4133120000
4  2019-01-08  2574.409912  2579.820068  2547.560059  2568.110107  4120060000

In [6]:
#data type 
for name, df in datasets.items():

    print(f"\n{name}")

    print(df.dtypes)

Bitcoin
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

Ethereum
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

Gold
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

SP500
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [7]:
#missing value
missing_summary = pd.DataFrame()

for name, df in datasets.items():

    missing_summary[name] = df.isnull().sum()

missing_summary

        Bitcoin  Ethereum  Gold  SP500
Date          0         0     0      0
Close         0         0     0      0
High          0         0     0      0
Low           0         0     0      0
Open          0         0     0      0
Volume        0         0     0      0

In [8]:
#duplicate record
for name, df in datasets.items():

    print(name)

    print("Duplicate Rows:", df.duplicated().sum())

Bitcoin
Duplicate Rows: 0
Ethereum
Duplicate Rows: 0
Gold
Duplicate Rows: 0
SP500
Duplicate Rows: 0

In [9]:
#date range for name, df in datasets.items():
for name, df in datasets.items():
    print(name)

    print(
        df["Date"].min(),
        "to",
        df["Date"].max()
    )

Bitcoin
2019-01-01 to 2024-12-31
Ethereum
2019-01-01 to 2024-12-31
Gold
2019-01-02 to 2024-12-31
SP500
2019-01-02 to 2024-12-31

## DATA CLEANING

In [10]:
# convert date
for df in datasets.values():

    df["Date"] = pd.to_datetime(df["Date"])
#sort data
for df in datasets.values():

    df.sort_values("Date", inplace=True)

    df.reset_index(drop=True, inplace=True)

In [11]:
#data type 
for name, df in datasets.items():

    print(f"\n{name}")

    print(df.dtypes)

Bitcoin
Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

Ethereum
Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

Gold
Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

SP500
Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

In [12]:
#add asset column 
bitcoin["Asset"] = "Bitcoin"

ethereum["Asset"] = "Ethereum"

gold["Asset"] = "Gold"

sp500["Asset"] = "SP500"

## DATA INTEGRATION

In [13]:
master_df = pd.concat(
    [bitcoin,
     ethereum,
     gold,
     sp500],
    ignore_index=True
)
master_df.sort_values(
    ["Date", "Asset"],
    inplace=True
)

master_df.reset_index(
    drop=True,
    inplace=True
)

In [14]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7404 entries, 0 to 7403
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    7404 non-null   datetime64[ns]
 1   Close   7404 non-null   float64
 2   High    7404 non-null   float64
 3   Low     7404 non-null   float64
 4   Open    7404 non-null   float64
 5   Volume  7404 non-null   int64
 6   Asset   7404 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 405.0+ KB

In [15]:
master_df.head()

,Date,Close,High,Low,Open,Volume,Asset
0,2019-01-01,3843.520020,3850.913818,3707.231201,3746.713379,4324200990,Bitcoin
1,2019-01-01,140.819412,141.397507,132.650711,133.418152,2258709868,Ethereum
2,2019-01-02,3943.409424,3947.981201,3817.409424,3849.216309,5244856836,Bitcoin
3,2019-01-02,155.047684,156.929138,140.650955,141.519516,3328240369,Ethereum
4,2019-01-02,121.330002,121.750000,120.879997,121.349998,12776200,Gold

In [16]:
master_df.tail()

,Date,Close,High,Low,Open,Volume,Asset
7399,2024-12-30,5906.939941,5940.790039,5869.160156,5920.669922,3433250000,SP500
7400,2024-12-31,93429.203125,96090.601562,91914.031250,92643.250000,43625106843,Bitcoin
7401,2024-12-31,3332.531738,3444.396729,3311.412598,3356.394775,20845452085,Ethereum
7402,2024-12-31,242.130005,242.520004,241.050003,241.050003,2522100,Gold
7403,2024-12-31,5881.629883,5929.740234,5868.859863,5919.740234,3128350000,SP500

In [18]:
#Saving Master
master_df.to_csv(
    PROCESSED_DATA_PATH /
    "market_data_master.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.

# Summary

The raw datasets were successfully validated, cleaned, and integrated into a single master dataset.

The processed dataset is now standardized and ready for exploratory data analysis.

### Output

- market_data_master.csv

### Next Notebook

03_exploratory_data_analysis.ipynb